#ifndef GUARD_CONSTANTS_EVOLUTION_SCENE_H
#define GUARD_CONSTANTS_EVOLUTION_SCENE_H

#define MILCERY_EVO_ITEM_OFFSET 238
#define MILCERY_EVO_ITEM_COUNT 7
#define MILCERY_EVO_DURATION_COUNT 3
#define MILCERY_EVO_DIRECTION_COUNT 2

#endif  // GUARD_CONSTANTS_EVOLUTION_SCENE_H
