#ifndef GUARD_CONSTANTS_OUTFITS_H
#define GUARD_CONSTANTS_OUTFITS_H

//! macro modes

#define OUTFIT_MENU_CHECK_UNLOCKED 0
#define OUTFIT_MENU_CHECK_LOCKED   1
#define OUTFIT_MENU_CHECK_USED     2

#define OUTFIT_MENU_BUFFER_NAME    0
#define OUTFIT_MENU_BUFFER_DESC    1

//! outfits lists
#define OUTFIT_USUAL_GREEN 0
#define OUTFIT_UNUSUAL_RED 1
#define OUTFIT_COUNT 2

#define OUTFIT_BEGIN OUTFIT_USUAL_GREEN
#define OUTFIT_END   OUTFIT_UNUSUAL_RED

#define DEFAULT_OUTFIT OUTFIT_USUAL_GREEN

#endif //! GUARD_CONSTANTS_OUTFITS_H
