#ifndef STARTER_CHOOSE_CONSTANTS_H
#define STARTER_CHOOSE_CONSTANTS_H

#define REGION_MAX_NAME_LENGTH 6

#define REGION_KANTO 0
#define REGION_JOHTO 1
#define REGION_HOENN 2
#define REGION_SINNOH 3
#define REGION_UNOVA 4
#define REGION_KALOS 5
#define REGION_ALOLA 6
#define REGION_GALAR 7
#define REGION_PALDEA 8

#define REGION_COUNT 9

#endif // STARTER_CHOOSE_CONSTANTS_H
