blank_issues_enabled: false
contact_links:
  - name: Rom-Hacking Hideout's Discord server!
    url: https://discord.gg/6CzjAG6GZk
    about: You can follow the development of pokeemerald-expansion and be notified of new releases :)