OldaleTown_House3_MapScripts::
	.byte 0


OldaleTown_House3_EventScript_Scientist::
	msgbox OldaleTown_House3_EventScript_Scientist_Text_0, MSGBOX_NPC
	return


OldaleTown_House3_EventScript_Scientist_Text_0:
	.string "Thanks to new technology, you can now\n"
	.string "see your Pokémon's Effort Values (EVs)\l"
	.string "by pressing the L Button while viewing\l"
	.string "their stats.\p"
	.string "You can also view their Individual\n"
	.string "Values (IVs) by pressing the R Button\l"
	.string "while viewing their stats.$"
