RustboroCity_Flat3_2F_MapScripts::
	.byte 0


RustboroCity_Flat3_2F_EventScript_Man4::
	msgbox RustboroCity_Flat3_2F_EventScript_Man4_Text_0, MSGBOX_NPC
	return


RustboroCity_Flat3_2F_EventScript_Man3::
	msgbox RustboroCity_Flat3_2F_EventScript_Man3_Text_0, MSGBOX_NPC
	return


RustboroCity_Flat3_2F_EventScript_Man4_Text_0:
	.string "Have you heard of Mega Evolution? I\n"
	.string "heard it makes certain Pokémon\l"
	.string "frighteningly strong.$"

RustboroCity_Flat3_2F_EventScript_Man3_Text_0:
	.string "If you want to Mega Evolve a Pokémon,\n"
	.string "you're going to need a Mega Ring.$"
