OmaomaTown_House2_MapScripts::
	.byte 0


OmaomaTown_House2_EventScript_Woman4::
	msgbox OmaomaTown_House2_EventScript_Woman4_Text_0, MSGBOX_NPC
	return


OmaomaTown_House2_EventScript_Woman3::
	msgbox OmaomaTown_House2_EventScript_Woman3_Text_0, MSGBOX_NPC
	return


OmaomaTown_House2_EventScript_Woman4_Text_0:
	.string "Oma'oma started off small, but now it's\n"
	.string "even bigger than Dewford Town.$"

OmaomaTown_House2_EventScript_Woman3_Text_0:
	.string "Alola! Catch any neat Pokémon lately?$"
