name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev libelf-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Poryscript Download
        uses: robinraju/release-downloader@v1
        with:
          repository: 'huderlem/poryscript'
          latest: true
          fileName: 'poryscript-linux.zip'
          extract: true
          out-file-path: 'tools'

      - name: Poryscript Install
        run: |
          sudo mv tools/poryscript-linux tools/poryscript
          sudo chmod +x tools/poryscript/poryscript

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O all
